const imageBookUrl = "https://pbs.twimg.com/media/FWJSkUgVUAEmoON?format=jpg&name=4096x4096";
const imageFanArtsUrl = [
    "https://pbs.twimg.com/media/FVsRKx9aAAAB6T8?format=jpg&name=large",
    "https://pbs.twimg.com/media/FV7ymOZaMAACyC8?format=jpg&name=large",
    "https://pbs.twimg.com/media/FVr2SoRaMAAsnLT?format=jpg&name=large",
    "https://pbs.twimg.com/media/FWHQhryakAE6JBw?format=jpg&name=large",
    "https://pbs.twimg.com/media/FWCVk85aMAAVlRN?format=jpg&name=4096x4096",
    "https://pbs.twimg.com/media/FVgyh5YVIAEuHoR?format=jpg&name=large",
    "https://pbs.twimg.com/media/FVntOnlUcAEiJz1?format=jpg&name=large",
    "https://pbs.twimg.com/media/FV3szByakAACnTl?format=jpg&name=large",
    "https://pbs.twimg.com/media/FVnfxLsaUAEXXKL?format=jpg&name=large",
    "https://pbs.twimg.com/media/FWGoZ6GUIAAWtMc?format=jpg&name=large",
    "https://pbs.twimg.com/media/FVioYWeakAElPAB?format=jpg&name=large",
    "https://pbs.twimg.com/media/FV-j_0LUAAAGN3K?format=jpg&name=large",
    "https://pbs.twimg.com/media/FWEnTG8UUAA9_-s?format=jpg&name=large",
    "https://pbs.twimg.com/media/FV66cIfUYAAhu0i?format=jpg&name=medium",
    "https://pbs.twimg.com/media/FVq04gcUcAERKRT?format=jpg&name=4096x4096",
    "https://pbs.twimg.com/media/FT2l-rCaMAAH3uc?format=png&name=900x900",
    "https://pbs.twimg.com/media/FWFSsrMWYAYG-Ob?format=jpg&name=900x900",
    "https://pbs.twimg.com/media/FV3gDCnaMAAGaqG?format=jpg&name=large",
    "https://pbs.twimg.com/media/FWKngMVaAAIdpiy?format=jpg&name=large",
    "https://pbs.twimg.com/media/FVc5c2fUAAIeDlr?format=jpg&name=4096x4096",
    "https://pbs.twimg.com/media/FVak003XoAAzYps?format=jpg&name=4096x4096",
    "https://pbs.twimg.com/media/FV_pSkFUcAAi_RG?format=jpg&name=large",
    "https://pbs.twimg.com/media/FVu32BMUEAA0fQQ?format=jpg&name=large",
    "https://pbs.twimg.com/media/FWD5PVnaIAAv5dW?format=jpg&name=900x900",
    "https://pbs.twimg.com/media/FV17FrvUAAAjsPK?format=jpg&name=4096x4096",
    "https://pbs.twimg.com/media/FVhZB9FUAAAc0T_?format=jpg&name=large",
    "https://pbs.twimg.com/media/FWKyCBoUsAADft4?format=jpg&name=large",
    "https://pbs.twimg.com/media/FVaflHDVsAIsdC_?format=jpg&name=large",
    "https://pbs.twimg.com/media/FWFlomxagAEG4Qt?format=jpg&name=medium",
]

// CREDITS

const credits = [
    "sugar_7g",
    "HIYO_5353",
    "seanliao1998",
    "Fuyurnn",
    "zeri_la",
    "832faa",
    "strudlesuki",
    "clariKerli",
    "owaowabuttercup",
    "penpen_kaseli",
    "Nody_Ara",
    "RchySzc",
    "FrozenduckArt",
    "ZetsuenTAl",
    "MoZenjin",
    "M0a_",
    "Nayla1447255737",
    "rupabiru",
    "I_am_Hinatsuki",
    "Taiyo_081",
    "KOJAKU_KUN",
    "Hawakawa333",
    "belsanchan",
    "Dian4_1",
    "IndhiUburz",
    "Rei__Xafa",
    "BebySeredova",
    "ZerlinaArgya",
    "gunawan_indar",
]

export { imageBookUrl, imageFanArtsUrl, credits}
